version: '2'

run:
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: false

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - mnd
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: -1
      statements: 50
      ignore-comments: true
    goconst:
      min-len: 2
      min-occurrences: 2
      numbers: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      settings:
        rangeValCopy:
          sizeThreshold: 164
          skipTestFuncs: true
        captLocal:
          paramsOnly: false
        elseif:
          skipBalanced: false
        hugeParam:
          sizeThreshold: 70
        ifElseChain:
          minThreshold: 2
        nestingReduce:
          bodyWidth: 5
    gocyclo:
      min-complexity: 12
    godot:
      scope: declarations
      exclude:
        - '^TODO:'
      capital: true
      period: true
    gosec:
      excludes:
        - G204
        - G304
      severity: low
      confidence: low
    govet:
      disable:
        - shadow
    lll:
      line-length: 200
      tab-width: 1
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
