list-indent: true
ul-start-left: true
ul-indent:
  indent: 2
no-hard-tabs: true
no-trailing-spaces: true
no-reversed-links: true
no-multiple-blanks: false
line-length:
  line_length: 350
  code_blocks: false
  tables: false
commands-show-output: true
no-missing-space-atx: true
no-multiple-space-atx: true
no-missing-space-closed-atx: true
no-multiple-space-closed-atx: true
blanks-around-headers: false
header-start-left: true
no-duplicate-header: true
single-h1: true
no-trailing-punctuation:
  punctuation: '.,;:!'
no-multiple-space-blockquote: true
no-blanks-blockquote: true
ol-prefix:
  style: one_or_ordered
list-marker-space: true
blanks-around-fences: false
blanks-around-lists: false
no-bare-urls: true
hr-style:
  style: '---'
no-emphasis-as-header: true
no-space-in-emphasis: true
no-space-in-code: true
no-space-in-links: true
fenced-code-language: false
first-line-h1: false
no-empty-links: true
