name: 'bicep-docs'
author: 'Christos Galanopoulos'
description: 'Generate documentation for Bicep templates'
branding:
  icon: file-text
  color: blue
inputs:
  input:
    description: 'Input Bicep file or directory'
    required: false
    default: '.'
  output:
    description: 'Output Markdown file; ignored if input is a directory'
    required: false
    default: 'README.md'
  verbose:
    description: 'Verbose output'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input }}
    - ${{ inputs.output }}
    - ${{ inputs.verbose == 'true' && '--verbose' || '' }}
