name: 'bicep-docs'
author: 'Christos Galanopoulos'
description: 'Generate documentation for Bicep modules'
branding:
  icon: refresh-cw
  color: blue
inputs:
  input:
    description: 'Input file or directory'
    required: false
    default: '.'
  output:
    description: 'Output Markdown file; ignored if input is a directory'
    required: false
    default: 'README.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --input=${{ inputs.input }}
    - --output=${{ inputs.output }}
