name: 'bicep-docs'
author: 'Christos Galanopoulos'
description: 'Generate documentation for Bicep modules'
branding:
  icon: refresh-cw
  color: blue
inputs:
  command:
    description: 'The command to run (scan or update)'
    required: true
  path:
    description: 'The path to the bicep file or directory'
    required: false
  include-preview:
    description: 'Include preview API versions'
    required: false
    default: 'false'
  summary:
    description: 'Show action summary'
    required: false
    default: 'false'
  outdated:
    description: 'Only show outdated resources (only for scan command)'
    required: false
    default: 'false'
  output:
    description: 'The output format (normal | table | markdown) (only for scan command)'
    required: false
    default: 'normal'
  in-place:
    description: 'Overwrite the input file(s) (only for update command)'
    required: false
    default: 'true'
  silent:
    description: 'Silent output (only for update command)'
    required: false
    default: 'false'
outputs:
  result:
    description: 'The complete result from the bicep-docs command being run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - --path=${{ inputs.path }}
    - --include-preview=${{ inputs.include-preview }}
    - --outdated=${{ inputs.outdated }}
    - --output=${{ inputs.output }}
    - --in-place=${{ inputs.in-place }}
    - --silent=${{ inputs.silent }}
    - --summary=${{ inputs.summary }}
