ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

# Enable all available rules
enableAllRules = true

# Disabled rules
[rule.file-header]
    Disabled = true
[rule.function-length]
    Disabled = true
[rule.banned-characters]
    Disabled = true
[rule.cyclomatic]
    Disabled = true
[rule.cognitive-complexity]
    Disabled = true
[rule.flag-parameter]
    Disabled = true
[rule.empty-lines]
    Disabled = true
[rule.add-constant]
    Disabled = true
[rule.deep-exit]
    Disabled = true
[rule.comment-spacings]
    Disabled = true

# Rule tuning

## Argument limit
[rule.argument-limit]
    Arguments = [5]
[rule.function-result-limit]
    Arguments = [3]

## Max elements
[rule.max-public-structs]
    Arguments = [4]

## Length
[rule.line-length-limit]
    Arguments = [200]

## Error handling
[rule.unhandled-error]
    Arguments = ["fmt.Printf", "fmt.Println", "fmt.Fprintf", "fmt.Fprintln"]