version: "3"

tasks:
  #### Default ####

  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  #### Utility ####

  setup:
    desc: Run all setup tasks
    cmds:
      - task setup:mod
      - task setup:go-tools
    silent: true

  setup:mod:
    desc: Download and tidy Go modules
    aliases:
      - "mod"
    cmds:
      - go mod download
      - go mod tidy
    silent: true

  setup:go-tools:
    desc: Install necessary Go tools
    aliases:
      - "tools"
    cmds:
      - go install github.com/mgechev/revive@latest # revive for linting
      - go install gotest.tools/gotestsum@latest # gotestsum for testing
      - go install github.com/axw/gocov/gocov@latest # gocov for coverage
      - go install github.com/AlekSi/gocov-xml@latest # gocov-xml for coverage
      - go install golang.org/x/vuln/cmd/govulncheck@latest # govulncheck for security
      - go install github.com/securego/gosec/v2/cmd/gosec@latest # gosec for security

    silent: true

  #### Lint ####

  lint:
    desc: Run all lint tasks
    cmds:
      - task lint:fmt
      - task lint:vet
      - task lint:revive
    silent: true

  lint:fmt:
    desc: Format code
    aliases:
      - "fmt"
      - "format"
    cmds:
      - gofmt -s -w -l .
    silent: true

  lint:vet:
    desc: Vet code
    aliases:
      - "vet"
    cmds:
      - go vet ./internal/*
      - go vet ./cmd/*
    silent: true

  lint:revive:
    desc: Lint code with revive
    aliases:
      - "rv"
      - "revive"
    cmds:
      - revive -config revive.toml -formatter friendly ./internal/*
      - revive -config revive.toml -formatter friendly ./cmd/*
    silent: true

  #### Test ####

  test:
    desc: Run all tests for all packages
    cmds:
      - printf "---------- bicep ---------------------------------\n\n" && task test:bicep && printf "\n\n"
      - printf "---------- apiversions ---------------------------\n\n" && task test:apiversions && printf "\n\n"
    silent: true

  test:junit:
    desc: Run all tests for all packages and output JUnit XML
    vars:
      FILENAME: test-results.xml
    cmds:
      - task test
      - gotestsum --junitfile {{ .FILENAME }} --junitfile-project-name bicep-docs --junitfile-testcase-classname short --junitfile-testsuite-name short --junitfile-hide-empty-pkg --format-hide-empty-pkg
    silent: true

  test:bicep:
    desc: Run tests for bicep package
    dir: ./internal/bicep
    cmds:
      - gotestsum -f testname
    silent: true

  test:apiversions:
    desc: Run tests for apiversions package
    dir: ./internal/apiversions
    cmds:
      - gotestsum -f testname
    silent: true

  benchmark:
    desc: Run all benchmarks for all packages
    cmds:
      - printf "---------- apiversions ---------------------------\n\n" && task benchmark:apiversions && printf "\n\n"
    silent: true

  benchmark:apiversions:
    desc: Run benchmarks for apiversions package
    dir: ./internal/apiversions
    cmds:
      - go test -bench=. -benchmem -run=^Test -count 2
    silent: true

  coverage:
    desc: Generate coverage information for all packages
    cmds:
      - gocov test ./... | gocov report
    silent: true

  coverage:junit:
    desc: Generate coverage information for all packages
    vars:
      FILENAME: coverage.xml
    cmds:
      - gocov test ./... | gocov-xml > {{ .FILENAME }}
    silent: true

  coverage:badge:
    desc: Generate coverage badge
    cmds:
      - .github/scripts/coverage-badge.sh

  #### Security ####

  security:
    desc: Run all security tasks
    cmds:
      - task security:gosec
      - task security:govulncheck
    silent: true

  security:gosec:
    desc: Run gosec
    aliases:
      - "gosec"
    cmds:
      - gosec -exclude=G104,G107,G118 ./internal/...
      - gosec -exclude=G104,G107,G118 ./cmd/...
    silent: true

  security:govulncheck:
    desc: Run govulncheck
    aliases:
      - "govulncheck"
    cmds:
      - govulncheck ./...
      - task build
      - govulncheck -mode=binary ./bin/bicep-docs
    silent: true

  #### Build ####

  build:
    desc: Build binary
    cmds:
      - go build -o ./bin/bicep-docs ./cmd/bicep-docs/main.go
    silent: true

  #### Clean ####

  clean:
    desc: Clean binaries
    aliases:
      - "clean"
    cmds:
      - rm ./bin/bicep-docs 2> /dev/null
      - rm -rf ./dist 2> /dev/null
    silent: true
    ignore_error: true
