version: '3'

tasks:
  #### Default ####
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  #### Utility ####
  setup:
    desc: Run all setup tasks
    cmds:
      - task setup:mod
      - task setup:lint
      - task setup:test
    silent: true

  setup:mod:
    desc: Download and tidy Go modules
    cmds:
      - go mod download
      - go mod tidy
    silent: true

  setup:lint:
    desc: Install necessary linting tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    silent: true

  setup:test:
    desc: Install necessary testing tools
    cmds:
      - go install gotest.tools/gotestsum@latest
      - go install golang.org/x/tools/cmd/deadcode@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
    silent: true

  #### Lint ####
  lint:
    desc: Run golangci-lint
    cmd: golangci-lint run ./...
    silent: true

  #### Test ####
  test:
    desc: Run all tests for all packages
    cmds:
      - printf "---------- template ----------------------\n\n" && task test:template && printf "\n\n"
      - printf "---------- markdown ----------------------\n\n" && task test:markdown && printf "\n\n"
      - printf "---------- cli ---------------------------\n\n" && task test:cli && printf "\n\n"
    silent: true

  test:cli:
    desc: Run tests for cli package
    dir: ./internal/cli
    cmd: gotestsum -f testname
    silent: true

  test:markdown:
    desc: Run tests for markdown package
    dir: ./internal/markdown
    cmd: gotestsum -f testname
    silent: true

  test:template:
    desc: Run tests for template package
    dir: ./internal/template
    cmd: gotestsum -f testname
    silent: true

  deadcode:
    desc: Run deadcode
    cmd: deadcode ./...
    silent: true

  security:
    desc: Run gosec
    cmd: gosec -conf .gosec.json ./...
    silent: true

  coverage:
    desc: Generate coverage information for all packages
    cmd: go test -cover ./internal/markdown ./internal/template ./internal/cli
    silent: true

  coverage:markdown:
    desc: Generate coverage information for markdown package
    cmds:
      - go test -coverprofile=coverage.out ./internal/markdown
      - go tool cover -func=coverage.out
      - rm coverage.out
    silent: true

  coverage:template:
    desc: Generate coverage information for template package
    cmds:
      - go test -coverprofile=coverage.out ./internal/template
      - go tool cover -func=coverage.out
      - rm coverage.out
    silent: true

  ### Benchmark ###
  benchmark:
    desc: Run benchmarks for all packages
    cmds:
      - task benchmark:cli
      - task benchmark:template
    silent: true

  benchmark:cli:
    desc: Run benchmarks for cli package
    dir: ./internal/cli
    cmd: go test -run=^$ -bench=^BenchmarkGenerateDocs$ -benchmem
    silent: true

  benchmark:template:
    desc: Run benchmarks for template package
    dir: ./internal/markdown
    cmd: go test -run=^$ -bench=^BenchmarkParseTemplates$ -benchmem
    silent: true

  #### Build ####
  build:
    desc: Build binary
    cmds:
      - go build -o ./bin/bicep-docs ./cmd/bicep-docs/main.go
    silent: true

  #### Clean ####
  clean:
    desc: Clean binaries
    cmd: rm ./bin/bicep-docs 2> /dev/null
    silent: true
    ignore_error: true
